### PR TITLE
Updated theme to be lighter and orange

### LINKED ISSUE #1: Port current vimperator.org website to gh-pages
@apheleia if you can help out that would be awesome.

We can probably just rely on github's automatic conversion of markdown files into pages.

You can see the current README.md when you go to `vimperator.github.io`.

### LINKED ISSUE #4: Add favicon
The favicon should be copied from the old vimperator.org page.

### PR DESCRIPTION
**Pull request by schemar**
- Added lsav theme (https://github.com/lsav/lsav.github.io)
- Increased width from original theme
- Colours are now vimperator orange
- Added more menu items than original theme
- Logo is now vimperator png instead of gravatar
- Download button is now created by an include
- Removed "menu" include at the top of every page

Fixes #1 and fixes #4 

@maxauthority:
- I did not include a "Blog" menu item, as the blog hasn't been moved and you said it is not important for now. Instead I made 6 menu points that resemble more or less the current structure.
- I increased the width, as you disliked the small width of the previous theme

To bring the page to the state of the current vimperator.org page, the new content about other projects is still missing. I will start work on that right now, should be quick.

I think switching soon(ish) would be nice to enable everyone to easily contribute to the page.

### CODE REVIEW

**Comment by maxauthority** [comment]
Thanks, looks good on the first view! And we can still tweak which menu items we want to have over time ( I especially think "developer info" should go to github), but this is a great start. I merged both pull requests and made a quick test and all important links/content is there.

So I'll setup vimperator.org to point towards that page and we can still do more tweaks later.

Thanks a lot for your work!

**Comment by schemar** [comment]
Great! I am really happy I could contribute.

**Comment by schemar** [comment]
There should probably be a link in the footer or somewhere else to point to this github project, I forgot about that.

**Comment by maxauthority** [comment]
Yeah, we should also give credit to the original theme(s) used for the
homepage.

Now that the theme is implemented, I plan to update the homepage anyway in
the near future, as I am still not fully happy with the mostly redundant
content on Projects and then the separate Vimperator/Muttator pages. Maybe
we can merge them into one, but that certainly needs a good image carousel
script, so we can show multiple screenshots without bloating the page's
size.

**Comment by schemar** [comment]
Yes, definitely. An image carousel is also a good idea. Scripts are very easy to add.

You can also check out the mobile version, as the theme is responsive now. Unfortunately, this also means two separate menu sections in the header include. Regular and mobile.

**Pull request merged**
